name: Build EN App APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Verify Java
      run: |
        java -version
        echo $JAVA_HOME

    - name: Install system dependencies
      run: |
        sudo apt-get update

        sudo apt-get install -y \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-dev \
          git \
          zip \
          unzip \
          autoconf \
          automake \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          cmake \
          libffi-dev \
          libssl-dev \
          build-essential \
          ccache \
          libltdl-dev

    - name: Fix libtoolize
      run: |
        sudo ln -sf /usr/bin/libtoolize /usr/bin/glibtoolize || true

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install cython==0.29.37
        pip install buildozer
        pip install virtualenv

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses || true
 
    - name: Full clean
      run: |
        rm -rf .buildozer
        rm -rf ~/.buildozer
        rm -rf bin
        rm -rf .gradle

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: EN-App-APK
        path: bin/*.apk
